version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GRPC_DNS_RESOLVER=native
      - PYTHONUNBUFFERED=1
      - GRPC_TRACE=all
      - GRPC_VERBOSITY=DEBUG
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: 