version: '3.8'

services:
  frontend:
    image: heinekrogstad/polisai:frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=https://polisai.ru
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

  backend:
    image: heinekrogstad/polisai:backend
    # ports:
    #   - "5001:5001"
    network_mode: host
    environment:
      - REDIS_URL=redis://redis:6379/0
      - YANDEX_API_KEY=AQVN1-dqbkcvx68Hrv-edeaub_M8zaRemUMDcf3X
      - YANDEX_FOLDER_ID=b1gb1ftmtfh3fviu2qas
      # Настройки gRPC в Dockerfile уже есть
      # - GRPC_DNS_RESOLVER=native
      # - GRPC_PYTHON_ENABLE_IPV6=0
    # sysctls:
    #   - net.ipv6.conf.all.disable_ipv6=1
    #   - net.ipv6.conf.default.disable_ipv6=1
    #   - net.ipv6.conf.lo.disable_ipv6=1
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data: 